[package]
name = "search-engine"
description = "Search engine made using TF-IDF statistics calculation"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.152"
serde_json = "1.0.93"
tiny_http = "0.12.0"
xml-rs = "0.8.4"
